# Install agent
- hosts: puppet_agent
  vars_files:
    - vars/puppet_agent.yml
  tasks:
    - name: "Remove old puppet-agent"
      import_tasks: tasks/remove_puppet5_agent.yml
      tags:
        - never
        - clean_up_after_puppet5

    - name: "Install puppet-agent"
      import_tasks: tasks/puppet_agent.yml
      tags:
        - always

    - name: "Manage certificates"
      import_tasks: tasks/manage_cert.yml
      tags:
        - allow_cert_management
        - never

# Install server
- hosts: puppet_server
  vars_files:
    - vars/puppet_server.yml

  handlers:
    - name: "Add handlers"
      import_tasks: tasks/handlers.yml

  tasks:
    - name: "Install puppet-server"
      import_tasks: tasks/puppet_server.yml

    - name: "Install puppetdb"
      import_tasks: tasks/puppetdb.yml
      when: puppetdb_enabled is defined and puppetdb_enabled

    - name: "Install nginx"
      import_tasks: tasks/nginx.yml
      when: nginx_proxy_enabled is defined and nginx_proxy_enabled

    - name: "Install r10k"
      import_tasks: tasks/r10k.yml
      tags:
        - r10k
