- name: "Add key for nginx repository"
  apt_key:
    state: present
    url: http://nginx.org/keys/nginx_signing.key
  when: ansible_os_family == "Debian"

- name: "Add nginx repository"
  apt_repository:
    state: present
    repo: "deb http://nginx.org/packages/ubuntu/ {{ ansible_lsb.codename }} nginx"
  when: ansible_distribution == "Ubuntu"

- name: Install nginx
  apt:
    state: latest
    pkg: nginx
    update_cache: yes
    cache_valid_time: 180
  when: ansible_os_family == "Debian"

- name: "Create directories for nginx"
  file:
    state: directory
    path: "/etc/nginx/{{ item.dir }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - dir: ssl
      mode: '0600'
    - dir: sites-available
      mode: '0755'
    - dir: sites-enabled
      mode: '0755'

- name: "Remove default nginx config"
  file:
    state: absent
    path: /etc/nginx/conf.d/default.conf
  notify: "reload nginx"

- name: "Add base nginx config"
  template:
    src: ../templates/etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: "reload nginx"

- name: "Add nginx-config for puppetserver"
  template:
    src: ../templates/etc/nginx/sites-available/puppet-proxy.conf.j2
    dest: /etc/nginx/sites-available/puppet-proxy.conf
    owner: root
    group: root
    mode: 0644
  notify: "reload nginx"

- name: "Enable nginx site"
  file:
    state: link
    src: "/etc/nginx/sites-available/puppet-proxy.conf"
    dest: "/etc/nginx/sites-enabled/puppet-proxy.conf"
  notify: "reload nginx"

- name: "Start nginx"
  service:
    state: started
    name: nginx
